CREATE TABLE users (
  user_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_name VARCHAR(32) NOT NULL,
  email VARCHAR(256) CHARACTER SET latin1 NOT NULL,
PRIMARY KEY (user_id),
UNIQUE (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

